# Generated by Django 3.0.4 on 2020-03-30 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0004_auto_20200328_1807'),
    ]

    operations = [
        migrations.CreateModel(
            name='passengers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstna', models.CharField(max_length=64)),
                ('lastna', models.CharField(max_length=64)),
                ('flights', models.ManyToManyField(blank=True, related_name='passenger', to='hello.flights')),
            ],
        ),
    ]
